def search_array(arr, integer)
  #loop through array
  counter = 0
  while counter < arr.length
  #at each value, return index if integer found
    return counter if arr[counter] == integer
    counter += 1
  end
end

arr = [42, 89, 23, 1]
p search_array(arr, 24)


# method takes number, returns array
def fib(num)
  #make empty array to store work and return
  array = []
  #if num >= 1, add 0 to the end of the array
  if num >= 1
    array << 0
  end

  #if num >= 2, add 1 to the end of the array
  if num >= 2
    array << 1
  end

  # for all other numbers, Each number in the array is the sum of the previous two numbers, except for the 0 and the 1, which we started out with.
  while array.length < num
    last = array[-1]
    second_to_last = array[-2]
    array << last + second_to_last
  end

  #return an array
  array
end

p fib(6)

#To verify your work: the last number in the array generated by fib(100) will be 218922995834555169026.

p fib(100)[-1] == 218922995834555169026
